spring:
  datasource:
    driver-class-name:
    username: testuser
    password: testpassword
    url: jdbc:postgresql://0.0.0.0:5432/lifecounter_db

  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  main:
    allow-bean-definition-overriding: true